#!/bin/bash
#PBS -N barand_coexpressionNetwork
#PBS -m ae
#PBS -M arand.3@buckeyemail.osu.edu
#PBS -l walltime=2:00:00
#PBS -l mem=16G
#PBS -l nodes=1:ppn=8
#PBS -j oe

cd ~/microArray_v_RNASeq
module load R-3.0.2

SCRIPT_DIR="CoexpressionNetworkRProject/"
#DATA_DIR="Data/"

#cd $PBS_O_WORKDIR
#cp ${SCRIPT_DIR}*.R $TMPDIR
#cp
#cd $TMPDIR


Rscript ${SCRIPT_DIR}main.R ${ARGS} > out.Rout
#R CMD BATCH --args ${ARGS} < ${SCRIPT_DIR}main.R > out.Rout

#cp out.dat $PBS_O_WORKDIR
